# Generated by Django 4.2.2 on 2023-06-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='officical_homepage',
            new_name='official_homepage',
        ),
    ]
